services:
  pawlib:
    build:
      context: .
      dockerfile: Dockerfile
    image: pawlib:latest
    container_name: pawlib
    
    # Podman GPU support (using CDI)
    # devices:
#      - nvidia.com/gpu=all
    
    # Mount volumes (note :Z for SELinux compatibility)
    volumes:
      - ./data:/workspace/data:Z
      - ./outputs:/workspace/outputs:Z
      - ./checkpoints:/workspace/checkpoints:Z
      - ./notebooks:/workspace/notebooks:Z
    
    # Keep container running
    stdin_open: true
    tty: true
    
    # Environment variables
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONUNBUFFERED=1
    
    # Working directory
    working_dir: /workspace

  # Optional: Jupyter notebook server
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    image: pawlib:latest
    container_name: pawlib-jupyter
    
    # devices:
#      - nvidia.com/gpu=all
    
    volumes:
      - ./data:/workspace/data:Z
      - ./outputs:/workspace/outputs:Z
      - ./checkpoints:/workspace/checkpoints:Z
      - ./notebooks:/workspace/notebooks:Z
    
    ports:
      - "8888:8888"
    
    command: >
      bash -c "pip install jupyter &&
               jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root"
    
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONUNBUFFERED=1
